# The URL the site will be built for
base_url = "https://awakecoding.com"

# The site title and description; used in feeds by default.
title = "AwakeCoding ☀️💻"
description = "awakecoding - Adventures of a CTO"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "DeepThought"

compile_sass = true

build_search_index = true

# RSS feed
generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
    { name = "tags", feed = true, paginate_by = 10 },
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

# Configuration of the link checker.
[link_checker]
skip_prefixes = [
    "https://twitter.com/",
]
skip_anchor_prefixes = [
    "https://visualstudio.microsoft.com/",
]

# Treat internal link problems as either "error" or "warn", default is "error"
internal_level = "error"

# Treat external link problems as either "error" or "warn", default is "error"
external_level = "error"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[extra]
chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts", name = "Posts", feed = true },
  { url = "$BASE_URL/tags", name = "Tags", feed = true },
 ]},
]

# Author details
[extra.author]
name = "Marc-André Moreau"
avatar = "/images/avatar.jpg"

# Social links
[extra.social]
github = "awakecoding"
linkedin = "mamoreau"
twitter = "awakecoding"
bluesky = "awakecoding.com"
email = "marcandre.moreau@gmail.com"
